data_2 = {
    "django": ["asgiref", "pytz", "sqlparse"],
    "aiodns": ["pycares", "cffi", "pycparser"],
    "aiohttp": [
        "async-timeout",
        "attrs",
        "chardet",
        "multidict",
        "typing-extensions",
        "yarl",
        "idna",
    ],
    "amqp": ["vine"],
    "astroid": ["lazy-object-proxy", "six", "wrapt"],
    "boto3": [
        "botocore",
        "jmespath",
        "s3transfer",
        "docutils",
        "python-dateutil",
        "urllib3",
        "six",
    ],
    "botocore": ["docutils", "jmespath", "python-dateutil", "urllib3", "six"],
    "cycler": ["six"],
    "django-admin-sortable2": ["django", "asgiref", "pytz", "sqlparse"],
    "django-appconf": ["django", "asgiref", "sqlparse"],
    "django-cacheops": [
        "django",
        "funcy",
        "redis",
        "six",
        "asgiref",
        "sqlparse",
        "async-timeout",
    ],
    "django-ckeditor": ["django-js-asset", "django", "asgiref", "sqlparse"],
    "django-compat": ["six"],
    "django-compressor": [
        "django-appconf",
        "rcssmin",
        "rjsmin",
        "six",
        "django",
        "asgiref",
        "sqlparse",
    ],
    "django-hijack": ["django-compat", "six"],
    "django-hijack-admin": [
        "django-compat",
        "django-hijack",
        "six",
        "django",
        "asgiref",
        "sqlparse",
    ],
    "django-imagekit": ["django-appconf", "pilkit", "six", "django", "asgiref", "sqlparse"],
    "django-import-export": [
        "django",
        "diff-match-patch",
        "tablib",
        "asgiref",
        "sqlparse",
        "markuppy",
        "odfpy",
        "openpyxl",
        "pyyaml",
        "xlrd",
        "xlwt",
        "defusedxml",
        "et-xmlfile",
    ],
    "django-modeltranslation": ["django", "six", "asgiref", "sqlparse"],
    "django-redis": ["django", "redis", "asgiref", "sqlparse", "async-timeout"],
    "django-storages": ["django", "asgiref", "sqlparse"],
    "django-taggit": ["django", "asgiref", "sqlparse"],
    "django-user-agents": ["django", "user-agents", "asgiref", "sqlparse", "ua-parser"],
    "django-cors-headers": ["django", "asgiref", "sqlparse"],
    "djangorestframework": ["django", "asgiref", "sqlparse"],
    "tifffile": ["numpy"],
    "traitlets": ["decorator", "ipython-genutils", "six"],
    "twilio": [
        "pyjwt",
        "pytz",
        "requests",
        "six",
        "certifi",
        "charset-normalizer",
        "idna",
        "urllib3",
    ],
    "user-agents": ["ua-parser"],
    "zope.event": ["setuptools"],
    "zope.interface": ["setuptools"],
    "slate3k": ["pdfminer3k", "ply"],
    "django-two-factor-auth": [
        "django",
        "django-formtools",
        "django-otp",
        "django-phonenumber-field",
        "qrcode",
        "asgiref",
        "sqlparse",
        "babel",
        "six",
    ],
    "facebook_business": [
        "aiohttp",
        "curlify",
        "pycountry",
        "requests",
        "six",
        "aiosignal",
        "async-timeout",
        "attrs",
        "charset-normalizer",
        "frozenlist",
        "multidict",
        "yarl",
        "setuptools",
        "certifi",
        "idna",
        "urllib3",
    ],
    "django-admin-logs": ["django", "asgiref", "sqlparse"],
    "google-auth": ["cachetools", "pyasn1-modules", "rsa", "setuptools", "six", "pyasn1"],
    "google-auth-oauthlib": [
        "google-auth",
        "requests-oauthlib",
        "cachetools",
        "pyasn1-modules",
        "rsa",
        "six",
        "urllib3",
        "oauthlib",
        "requests",
        "pyasn1",
        "certifi",
        "charset-normalizer",
        "idna",
        "google-auth",
        "requests-oauthlib",
        "cachetools",
        "pyasn1-modules",
        "rsa",
        "six",
        "urllib3",
        "oauthlib",
        "requests",
        "pyasn1",
        "certifi",
        "charset-normalizer",
        "idna",
    ],
    "gspread": [
        "google-auth-oauthlib",
        "google-auth",
        "requests-oauthlib",
        "cachetools",
        "pyasn1-modules",
        "rsa",
        "six",
        "urllib3",
        "oauthlib",
        "requests",
        "pyasn1",
        "certifi",
        "charset-normalizer",
        "idna",
    ],
    "stripe": ["requests", "certifi", "charset-normalizer", "idna", "urllib3"],
    "pandas": ["numpy", "python-dateutil", "pytz", "six"],
    "pysftp": ["paramiko", "bcrypt", "cryptography", "pynacl", "cffi", "pycparser"],
    "google-api-python-client": [
        "google-api-core",
        "google-auth-httplib2",
        "google-auth",
        "httplib2",
        "uritemplate",
        "googleapis-common-protos",
        "protobuf",
        "requests",
        "six",
        "cachetools",
        "pyasn1-modules",
        "rsa",
        "urllib3",
        "pyparsing",
        "certifi",
        "charset-normalizer",
        "idna",
        "pyasn1",
    ],
    "google-auth-httplib2": [
        "google-auth",
        "httplib2",
        "six",
        "cachetools",
        "pyasn1-modules",
        "rsa",
        "urllib3",
        "pyparsing",
        "pyasn1",
    ],
    "django-silk": [
        "django",
        "jinja2",
        "autopep8",
        "gprof2dot",
        "python-dateutil",
        "pytz",
        "requests",
        "sqlparse",
        "asgiref",
        "markupsafe",
        "pycodestyle",
        "tomli",
        "six",
        "certifi",
        "charset-normalizer",
        "idna",
        "urllib3",
    ],
    "qrcode[pil]": ["pillow", "six"],
    "marshmallow": ["packaging"],
    "django-debug-toolbar": ["django", "sqlparse", "asgiref"],
}